const COLLECTION_USER = "sys_user";
const COLLECTION_ORGANIZE = "sys_organize";
const COLLECTION_GROUP = "sys_group";
const COLLECTION_FORM_DEFINE = "sys_form_define";
const COLLECTION_SYS_FLOW_INSTANCE="sys_flow_instance";
const COLLECTION_SYS_FLOW_DEFINE="sys_flow_define";

module.exports = {
    COLLECTION_USER,
    COLLECTION_ORGANIZE,
    COLLECTION_GROUP,
    COLLECTION_FORM_DEFINE,
    COLLECTION_SYS_FLOW_INSTANCE,
    COLLECTION_SYS_FLOW_DEFINE
}