# docker-compose.yml

version: '3'
services:
  server:
    image: postgrest/postgrest
    ports:
      - "8030:3000"
    environment:
      PGRST_DB_URI: postgres://ankemao:supabase_klkl@localhost:5432/supabase
      PGRST_DB_SCHEMAS: public
      PGRST_DB_ANON_ROLE: app_user #In production this role should not be the same as the one used for the connection
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: supabase
      POSTGRES_USER: ankemao
      POSTGRES_PASSWORD: supabase_klkl
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8031:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:8030/
  # Uncomment this if you want to persist the data.
  # volumes:
  #   - "./pgdata:/var/lib/postgresql/data"